AUTH_SERVICE_NAME = 'sqs'
AUTH_REGION_NAME = 'us-east-1'

SES_MAX_MESSAGES = 10

SENDMAIL_POOL_SIZE = 10
DELIVERLIES_POOL_SIZE = 10
BOUNCES_POOL_SIZE = 10
COMPLAINTS_POOL_SIZE = 10

class QUEUES(object):
    SENDMAIL_QUEUE='SES_SENDMAIL_QUEUE'
    BOUNCES_QUEUE='SES_BOUNCES_QUEUE'
    COMPLAINTS_QUEUE='SES_COMPLAINTS_QUEUE'
    DELIVERIES_QUEUE='SES_DELIVERIES_QUEUE'

class MESSAGE_STATUS(object):
    ERROR=1
    QUEUED=2
    PUSHED=4
    DELIVERED=8
    BOUNCED=16
    COMPLAINTED=32

class ERRORS(object):
    MALFORMED=1
    DUPLICATE=2


# Redis prefixes
LOCAL_MESSAGE_ID_PREFIX = 'local_message_id:'
COMPLAINTED_EMAIL_HASH_PREFIX= 'complainted_email_hash:'
BOUNCED_EMAIL_HASH_PREFIX= 'bounced_email_hash:'
    
    
